### ISSUE TITLE
Chrome CORB policy blocks recipe image on main page from loading

### ISSUE THREAD

**Issue by James103** [WUTDAHACK/Unbreakable-Tools-Fabric#1]
The following recipe image on the main project page for the mod does not load correctly on Google Chrome `88.0.4324.104 (Official Build) (64-bit) (cohort: Stable)` because of the following error:
```
[WARNING] Cross-Origin Read Blocking (CORB) blocked cross-origin response https://imgur.com/a/wH5gMDo with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

The link that provides the image should point to `https://i.imgur.com/OeTiZWC.png` instead of `https://imgur.com/a/wH5gMDo`.

**Comment by WUTDAHACK** [comment]
Thank you for submitting this issue, I've changed the link of the picture.
