### ISSUE TITLE
[Fabric] Any enchanted book makes the item unbreakable

### ISSUE THREAD

**Issue by Fogrits** [WUTDAHACK/Unbreakable-Tools-Fabric#2]
![image](https://user-images.githubusercontent.com/14002834/107107933-1b806a00-6813-11eb-9914-5c18f5abbe45.png)

**Comment by WUTDAHACK** [comment]
After spending some time looking at the recipes, I gave up and just made a new unbreakable book that you can make the tool unbreakable with.


![](https://i.imgur.com/c6kavEH.png)
That's the recipe for the book and the newest 1.16.5 version has it, hopefully it fixes the problem!

oh and to make the tool unbreakable it has the same recipe as the enchanted book one just instead it has a unbreakable book in it instead
