### ISSUE TITLE
Tools doesn't break modded ores

### ISSUE THREAD

**Issue by Fogrits** [WUTDAHACK/Unbreakable-Tools-Fabric#3]
https://user-images.githubusercontent.com/14002834/107175343-56b5a100-69ab-11eb-8b29-6ce254ea40d8.mp4

**Comment by Fogrits** [comment]
If I try to mine it until it breaks, nothing drops.

**Comment by Fogrits** [comment]
ps: I can break these ores with a stone pickaxe.

**Comment by WUTDAHACK** [comment]
Is the block meant to drop itself? I've added tool tags as the wiki says and I've tested it with the exact same block and pickaxe and it drops itself now.

**Comment by Fogrits** [comment]
> Is the block meant to drop itself? I've added tool tags as the fabric wiki says and I've tested it with the exact same block and pickaxe and it drops itself now.

Yes but it also happens with modded ores that drops something else, like dusts or crystals

**Comment by WUTDAHACK** [comment]
Oh ok, I'm going to upload a new version to Curseforge that should fix modded blocks not dropping. Tell me if it fixes it!

**Comment by Fogrits** [comment]
Unfortunately, It didn't.

https://user-images.githubusercontent.com/14002834/107218842-f3e5f900-69ee-11eb-969f-163fb0df5a4e.mp4

**Comment by Fogrits** [comment]
Wait, I just restarted and tried again, and somehow it got fixed LMAO

**Comment by Fogrits** [comment]
https://user-images.githubusercontent.com/14002834/107219248-91d9c380-69ef-11eb-9edf-c2a8091156d0.mp4

**Comment by WUTDAHACK** [comment]
XD Oh ok! I'm glad I could help!
